name: Automated Testing

on:
  workflow_call:


jobs:
  Test-Runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Installing Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Test-Runner Script
        run: |
          ./test-runner.sh
          # # Check the exit status of the tests and fail the workflow if they fail
          # if [ $? -ne 0 ]; then
          #   echo "Tests failed. Failing the workflow."
          #   exit 1
          # fi

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: build/test/Testing/Temporary

      - name: Display test logs
        if: failure()
        run: cat build/test/Testing/Temporary/LastTest.log
